---
title: "PSMatching"
author: "Zugui Zhang"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(tidyverse)
library(MatchIt)
library(lmtest)
library(sandwich)
library(tableone)
library(ROCR)
library(pROC)
library(randomForest)
library(randomForestSRC)
```

```{r}
setwd("C:/Users/zugui/Desktop/work/UDFall2022/ObservationalStudies")

currentDataset <- read.csv("currentDataset.csv")
names(currentDataset)
```
```{r}
table1 <- CreateTableOne(vars = c('sex' ,'indigeneity', 'high_school', 'partnered',  'remoteness', 'language','risky_alcohol','age'),
                         data = currentDataset,
                         factorVars = c('sex' ,'indigeneity', 'high_school', 'partnered',  'remoteness', 'language','risky_alcohol'),
                         strata = 'smoker',
                         test = TRUE,
                         smd=TRUE) #standardized mean differences)
table1 <- print(table1,
                smd=TRUE,
                showAllLevels = TRUE,
                noSpaces = TRUE,
                printToggle = FALSE)
table1

write.csv(table1, file ="tablesmoker.csv")
```
```{r}
#Since remoteness is a categorical variable with more than two categories. It is necessary to convert 
#it into a factor variable.
#For other categorical variable with only 2 levels, this is optional if the variable is coded as 0 and 1.
currentDataset$remoteness <- factor(currentDataset$remoteness, exclude = c("", NA))
#The MatchIt, lmtest and sandwich libraries are used.

#Using the mathcit function from MatchIt to match each smoker with a non-smoker (1 to 1 matching) based on
#sex, indigeneity status, high school completion, marital status (partnered or not),
#region of residence (major cities, inner regional, outer regional), language background (English speaking Yes/No) 
#and risky alcohol drinking (Yes/No)
modellogic <- glm(smoker ~ sex + indigeneity + high_school + partnered + remoteness + language + risky_alcohol + age, 
                  family="binomial", data=currentDataset)
predictionsStress <- predict(modellogic, type = "response")
cindex<-roc(currentDataset$smoker, predictionsStress)
cindex


ggroc(roc(currentDataset$smoker, predictionsStress)) +
  theme_minimal() + 
  ggtitle("Psychological Distress: ROC Curve" ) + 
  geom_segment(aes(x = 1, xend = 0, y = 0, yend = 1), color="blue", linetype="dashed")

pROC_obj <- roc(currentDataset$smoker, predictionsStress,
                smoothed = TRUE,
                # arguments for ci
                ci=TRUE, ci.alpha=0.9, stratified=FALSE,
                # arguments for plot
                plot=TRUE, auc.polygon=TRUE, max.auc.polygon=TRUE, grid=TRUE,
                print.auc=TRUE, show.thres=TRUE, main = "Psychological Distress: ROC Curve")

sens.ci <- ci.se(pROC_obj)
plot(sens.ci, type="shape", col="lightblue")
## Warning in plot.ci.se(sens.ci, type = "shape", col = "lightblue"): Low
## definition shape.
plot(sens.ci, type="bars")
```
```{r}
help(matchit)

match_obj <- matchit(smoker ~ sex + indigeneity + high_school + partnered + remoteness + language + risky_alcohol + age,
                     data = currentDataset, method = "nearest", distance ="glm",
                     ratio = 1,
                     replace = FALSE,
                     improvement = TRUE)
summary(match_obj, improvement = TRUE)
#plotting the balance between smokers and non-smokers
plot(match_obj, type = "jitter", interactive = FALSE)
plot(summary(match_obj), abs = FALSE)
match_obj$model

#Extract the matched data and save the data into the variable matched_data
matched_data <- match.data(match_obj)
names(matched_data)

table1matched <- CreateTableOne(vars = c('sex' ,'indigeneity', 'high_school', 'partnered',  'remoteness', 
                                         'language','risky_alcohol','age'),
                         data = matched_data,
                         factorVars = c('sex' ,'indigeneity', 'high_school', 'partnered',  'remoteness', 
                                        'language','risky_alcohol'),
                         strata = 'smoker',
                         test = TRUE,
                         smd=TRUE) #standardized mean differences)
table1matched <- print(table1matched,
                smd=TRUE,
                showAllLevels = TRUE,
                noSpaces = TRUE,
                printToggle = FALSE)
table1matched

write.csv(table1matched, file ="table1matched.csv")
```
```{r}

#Run regression model with psychological distress as the outcome, and smoker as the only predictor
res <- lm(psyc_distress ~ smoker, data = matched_data, weights = weights)
summary(res)

#res1 <- lm(psyc_distress ~ smoker, data = matched_data)

#Test the coefficient using cluster robust standard error
coeftest(res, vcov. = vcovCL, cluster = ~subclass)
#Calculate the confidence intervals based on cluster robust standard error
coefci(res, vcov. = vcovCL, cluster = ~subclass, level = 0.95)

resalldata <- lm(psyc_distress ~ smoker + sex + indigeneity + high_school + partnered + 
                   remoteness + language + risky_alcohol + age, 
              data = currentDataset)
summary(resalldata)

coeftest(resalldata)
coefci(resalldata, vcov. = vcovCL, level = 0.95)

#
match_rpart <- matchit(smoker ~ sex + indigeneity + high_school + partnered + remoteness + language + risky_alcohol + age,
                     data = currentDataset,  distance='rpart')
summary(match_rpart, improvement = TRUE)
match_rpart$model
matched_rpart <- match.data(match_rpart)

match_nnet <- matchit(smoker ~ sex + indigeneity + high_school + partnered + remoteness + language + risky_alcohol + age,
                 data = currentDataset, 
                 distance='nnet',
                 distance.options=list(size=16))
summary(match_nnet, improvement = TRUE)
matched_nnet <- match.data(match_nnet)

rf.out <- randomForest(smoker ~ sex + indigeneity + high_school + partnered + remoteness + language + risky_alcohol + age,
                       data = currentDataset)
rf.out 
eps <- rf.out$votes[,2] # Estimated PS
matchedrf<-matchit(formula=smoker ~ sex + indigeneity + high_school + partnered + remoteness + language + risky_alcohol + age,
        data = currentDataset, 
        distance='randomforest',, 
        method='nearest',
        replace=TRUE,
        discard='both',
        ratio=5)
summary(matchedrf, improvement = TRUE)
matched_nnet <- match.data(matchedrf)

matchedlasso<-matchit(formula=smoker ~ sex + indigeneity + high_school + partnered + remoteness + language + risky_alcohol + age,
                   data = currentDataset, 
                   distance='lasso',, 
                   method='nearest',
                   replace=TRUE,
                   discard='both',
                   ratio=2)
summary(matchedlasso, improvement = TRUE)
matched_nnet <- match.data(matchedlasso)
matched_nnet
```





