---
title: "Project Instructions"
author: "Manning Smith"
date: "11/6/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Part 1

A study was conducted to test the impact of new drug in treating hyperglycemia in patients with diabetes mellitus.  The primary outcome was the total number of deaths. The data consists of a total of more than 1200 patients, met eligibility criteria for the study for the randomized clinical trial (Triinhibitor vs. placebo), data dictionary is provided below.

The primary end point was the total number of deaths.

- Conduct survival analysis to examine the impact of Triinhibitor vs. placebo on the survival.  You should indicate how you will define the event, and estimate the survival curves using the Kaplan–Meier method.  Show your survival data with censored time, and perform a test for possible differences, i.e., conduct a suitable test to examine the effect of Triinhibitor vs. placebo.

- Conduct multivariate Cox Regression Analysis to examine the impact of the Triinhibitor vs. placebo and other factors on the risk of death using hazard ratios.

- Conduct a suitable test and a graphical diagnostic for the proportional hazards assumption for the used Cox Regression modelling.


## Import Data
### Data Dictionary of the dataset
- PID:    Patient ID
- Age:    in years
- Gender:   F/M, Female/Male
- Ethnicity:
  - HISPANIC OR LATINO
  - NOT HISPANIC OR LA
  - NOT REPORTED
- White:
  - 0:  White
  - 1:  Non-white
- LVEF:   Left ventricular ejection fraction
- A1c:    Average amount of glucose (sugar) in blood
- SBP:    Systolic blood pressure,  mm Hg
- DBP:    Diastolic blood pressure,  mm Hg
- BMI:    Body mass index $\frac{kg}{m^2}$
- Ischemic Status:
  - Ischemic
  - Non-Ischemic
- Reason of End the Study:
  - STUDY TERMINATED BY SPONSOR
  - DEATH
  - LOST TO FOLLOW-UP
  - PHYSICIAN DECISION
  - WITHDEAWAL BY SUBJECT
- Months of Follow-up:  In months
- Group:
  - Placebo
  - Triinhibitor
- GFR:    Glomerular filtration rate.

# Part 2

PRAMS, the Pregnancy Risk Assessment Monitoring System, is a surveillance project of the Centers for Disease Control and Prevention (CDC).  PRAMS collects state-specific, population-based data on maternal attitudes and experiences before, during, and shortly after pregnancy. PRAMS surveillance currently covers about 83% of all U.S. births.

## Questions
- Provide the structure of the data set, including length, data type, names, and the components of the data set.
- Examine variables with zero variance or near-zero variance;
- Explore the correlation matrix with visualization;
- Examine the missing-ness including the visualization of missing values, identifying variables that may need attention, and conducting the imputation for handling missing values in the data set, and showing part of the imputed results.

We will try to predict MH_PPDPR (MH: depress since birth) via methods we have learned this semester so far, using other variables (PGWT_GN: Pregnant weight gain/lost; MOM_CM:  Moms height – centimeters; MOM_BMI: MOM BODY MASS INDEX; MOMCIG:   Number of Cigarettes Per Day; CIG_PRIOR : No. of cigarettes smoked - prior to pregnant; and MOM_LBKG : Moms weight -- before pregnant); i.e: MH_PPDPR (MH: depress since birth) is the response (outcome, or target), and the predictors are PGWT_GN, MOM_CM, MOM_BMI, MOMCIG , CIG_PRIOR , MOM_LBKG, and DDS_INS(DDS – insurance).  Note that you should depart the data into training set and testing set.

- Propose a way to handle the outcome variable MH_PPDPR (MH: depress since birth);
- Conduct model selection procedure via suitable criteria;
- Conduct a type of generative model analysis, provide the results in prediction, and comments on your results;
- Conduct a type of instance-based learning analysis, provide the results in prediction, and comments on your results;
- Conduct a type of regularization analysis, provide the results in prediction, and comments on your results;

## Import Data
### Data Dictionary of the dataset
- ID:  Subject Identifier
- ALIVE:  1--infant alive; 2—infant not alive;
- BF5EVER: Breastfeed--ever, 1=No, 2=Yes.
- BF5LNGTH: duration -- length of time in weeks
- PGWT_GN: Pregnant weight gain/lost
- MOM_CM:  Moms height – centimeters
- MOM_BMI:  MOM BODY MASS INDEX
- MOMCIG:   Number of Cigarettes Per Day
- CIG_PRIOR : No. of cigarettes smoked - prior to pregnant 
- MOM_LBKG : Moms weight -- before pregnant
- DDS_INS DDS: insurance
  - .A = NOT APPLICABLE.B = DK/BLANK
  - .N = NOT RECORDED
  - .U = UNKNOWN
  - 1 = NO
  - 2 = YES
- MH_PPDPR MH: depress since birth
  - .B = BLANK/DK
  - .S = SKIP
  - 1 = ALWAYS
  - 2 = OFTEN/ALMOST ALWAYS
  - 3 = SOMETIMES
  - 4 = RARELY
  - 5 = NEVER